// initial_stories.js
// Diese Daten werden nur verwendet, wenn im LocalStorage noch gar keine Rätsel sind.
// IDs werden beim ersten Laden durch UUIDs ersetzt.
const initialStoriesData = [
    {
        id: "initial_1",
        title: "Der Mann im Fahrstuhl",
        difficulty: "Mittel",
        riddle: "Ein Mann wohnt im 10. Stock. Er fährt jeden Morgen mit dem Fahrstuhl bis ganz nach unten. Abends fährt er mit dem Fahrstuhl bis zum 7. Stock und geht den Rest zu Fuß. Warum? (Außer wenn es regnet, dann fährt er ganz hoch.)",
        solution: "Der Mann ist kleinwüchsig. Er erreicht nur den Knopf für den 7. Stock. Wenn es regnet, hat er seinen Regenschirm dabei und kann damit den Knopf für den 10. Stock drücken.",
    },
    {
        id: "initial_2",
        title: "Tödlicher Tauchgang",
        difficulty: "Schwer",
        riddle: "Ein Mann liegt tot in einem Wald. Neben ihm ein ungeöffnetes Paket.",
        solution: "Der Mann ist mit einem Fallschirm abgesprungen, der sich nicht geöffnet hat. Das Paket ist der Fallschirm.",
    },
    {
        id: "initial_3",
        title: "Die nackte Frau auf der Wiese",
        difficulty: "Leicht",
        riddle: "Eine nackte Frau liegt tot auf einer Wiese. Neben ihr ein Streichholz.",
        solution: "Sie war mit mehreren Personen in einem Heißluftballon. Der Ballon drohte abzustürzen. Sie zogen Streichhölzer, wer abspringen muss, um die anderen zu retten. Sie zog das kürzeste.",
    },
    {
        id: "initial_4",
        title: "Musik stoppte",
        difficulty: "Mittel",
        riddle: "Die Musik stoppte und sie starb. Erkläre.",
        solution: "Sie war eine Seiltänzerin im Zirkus, die mit verbundenen Augen tanzte. Die Musik gab ihr den Takt und die Orientierung vor. Als die Musik (vielleicht durch einen Stromausfall) plötzlich stoppte, verlor sie die Orientierung und stürzte ab.",
    },
    {
        id: "initial_5",
        title: "Der Mann im Auto",
        difficulty: "Leicht",
        riddle: "Ein Mann schiebt sein Auto bis zu einem Hotel und verliert daraufhin sein ganzes Vermögen. Was ist passiert?",
        solution: "Er spielt Monopoly und seine Spielfigur ist das Auto. Er landet auf einem Feld mit einem Hotel, das einem anderen Spieler gehört, und muss eine hohe Miete zahlen.",
    },
    {
        id: "initial_6",
        title: "Adam und Eva",
        difficulty: "Schwer",
        riddle: "Adam und Eva liegen tot in einem Raum. Es gibt keine Fenster und nur eine Tür, die von innen verschlossen ist. Auf dem Boden liegen Glasscherben und eine Wasserpfütze. Wie starben sie?",
        solution: "Adam und Eva sind Goldfische. Ihr Aquarium ist vom Tisch gefallen und zerbrochen.",
    },
    {
        id: "initial_7",
        title: "Der Schneemann",
        difficulty: "Mittel",
        riddle: "Auf einer Wiese liegen mehrere Karotten, ein Schal und zwei Kohlestücke. Niemand ist in der Nähe. Was ist passiert?",
        solution: "Dort stand ein Schneemann, der geschmolzen ist.",
    },
    {
        id: "initial_8",
        title: "Der Anruf",
        difficulty: "Mittel",
        riddle: "Ein Mann lebt allein in einem Haus. Eines Nachts schaltet er alle Lichter aus und geht schlafen. Am nächsten Morgen liest er in der Zeitung von einem Schiffsunglück und begeht Selbstmord. Warum?",
        solution: "Der Mann war Leuchtturmwärter. Indem er die Lichter (des Leuchtturms) ausschaltete, verursachte er das Schiffsunglück und fühlte sich schuldig.",
    },
    {
        id: "initial_9",
        title: "Die Frau im Hotel",
        difficulty: "Schwer",
        riddle: "Eine Frau checkt in einem Hotel ein. In der Nacht hört sie ein Klopfen an ihrer Tür, aber niemand ist da. Am nächsten Morgen checkt sie aus und bezahlt mit einer fremden Kreditkarte. Was ist los?",
        solution: "Die Frau ist eine Auftragsmörderin. Das Klopfen war das verabredete Zeichen für ihr Opfer (oder dass die Luft rein ist). Sie hat ihr Opfer im Nebenzimmer getötet und dessen Kreditkarte gestohlen.",
    },
    {
        id: "initial_10",
        title: "Fünf Männer",
        difficulty: "Leicht",
        riddle: "Fünf Männer gehen in eine Bar. Vier von ihnen kommen nass heraus, der fünfte bleibt trocken. Wie kann das sein?",
        solution: "Es hat angefangen zu regnen. Die vier Männer hatten keinen Schirm, der fünfte schon. (Oder der fünfte war der Barkeeper).",
    },
    {
        id: "initial_11",
        title: "Der Postbote",
        difficulty: "Mittel",
        riddle: "Ein Postbote mit Höhenangst muss einen Brief an eine Frau im 20. Stock eines Hochhauses zustellen. Der Fahrstuhl ist kaputt. Er schafft es trotzdem, ohne die Treppe zu benutzen. Wie?",
        solution: "Er wirft den Brief in den Briefkasten im Erdgeschoss.",
    },
    {
        id: "initial_12",
        title: "Marco Polo im Eis",
        difficulty: "Schwer",
        riddle: "Ein Mann namens Marco Polo wird tot in seinem Zimmer gefunden. Das Zimmer ist leer, bis auf einen Tisch und eine Pfütze Wasser. Die Tür war von innen verschlossen.",
        solution: "Marco Polo ist der Name eines Goldfisches. Er war in einem Eisblock eingefroren, der auf dem Tisch stand und geschmolzen ist.",
    },
    {
        id: "initial_13",
        title: "Der blinde Mann und die Suppe",
        difficulty: "Mittel",
        riddle: "Ein blinder Mann geht in ein Restaurant und bestellt Albatros-Suppe. Nach dem ersten Löffel geht er hinaus und erschießt sich. Warum?",
        solution: "Er war vor Jahren mit anderen auf einem Schiff gestrandet. Um zu überleben, wurde ihnen gesagt, sie äßen Albatros-Suppe. In Wirklichkeit aßen sie Fleisch von verstorbenen Kameraden. Als er im Restaurant echte Albatros-Suppe aß, erkannte er am Geschmack, dass er damals belogen und zum Kannibalen gemacht wurde.",
    },
    {
        id: "initial_14",
        title: "Der Zirkusdirektor",
        difficulty: "Leicht",
        riddle: "Der kleinste Mann der Welt liegt tot im Sägemehl eines Zirkuszelts. Was ist passiert?",
        solution: "Er war ein Flohzirkusdirektor und einer seiner 'Artisten' (ein Floh) ist gestorben, was ihn so traurig machte, dass er sich das Leben nahm. Oder: Er erstickte an einem übergroßen Popcorn.",
    },
    {
        id: "initial_15",
        title: "Die Kassette in der Wüste",
        difficulty: "Mittel",
        riddle: "Ein Mann liegt tot in der Wüste, neben ihm eine Kassette und ein Kassettenrekorder. Hätte er die Kassette gehört, wäre er nicht gestorben.",
        solution: "Er war der Pilot eines kleinen Flugzeugs, das abgestürzt ist. Die Kassette war das Band des Flugschreibers oder enthielt letzte Anweisungen/Informationen, die er nicht mehr hören konnte.",
    },
    {
        id: "initial_16",
        title: "Kein Entkommen?",
        difficulty: "Schwer",
        riddle: "Ein Mann ist in einem komplett leeren Raum eingesperrt. Es gibt keine Fenster, keine Türen und keine Werkzeuge. In der Mitte des Raumes steht nur ein Holztisch. Wie entkommt er?",
        solution: "Er reibt zwei Holzstücke des Tisches aneinander, bis ein Feuer entsteht. Mit dem Feuer macht er ein 'Licht'. Mit dem 'Licht' sieht er eine versteckte Tür. Oder: Er zerbricht den Tisch und benutzt die Splitter, um sich durchzugraben/die Wand zu bearbeiten. Die klassische ist oft spielerischer: Er isst den Tisch, bis er 'voller Tatendrang' ist und einen Ausweg findet. Oder: Er wartet, bis er verhungert, dann ist er 'leicht' genug, um durch ein Mauseloch zu passen (sehr schwarz).",
    },
    {
        id: "initial_17",
        title: "Der Mann an der Bar und der Schluckauf",
        difficulty: "Leicht",
        riddle: "Ein Mann geht in eine Bar und bittet den Barkeeper um ein Glas Wasser. Der Barkeeper zückt plötzlich eine Schrotflinte und zielt auf den Mann. Der Mann bedankt sich und geht. Warum?",
        solution: "Der Mann hatte Schluckauf. Der Schreck durch die Schrotflinte hat den Schluckauf beseitigt.",
    },
    {
        id: "initial_18",
        title: "Die Frau und der Sturm",
        difficulty: "Mittel",
        riddle: "Eine Frau stirbt, weil sie während eines Sturms das Telefon benutzt hat.",
        solution: "Sie telefonierte in der Badewanne während eines Gewitters. Ein Blitz schlug in die Telefonleitung ein und der Strom wurde durch das Wasser geleitet.",
    },
    {
        id: "initial_19",
        title: "Der Schal im Feld",
        difficulty: "Mittel",
        riddle: "Ein Mann wird tot in einem Feld gefunden, er trägt einen Schal. Es gibt keine Fußspuren um ihn herum.",
        solution: "Er war Eislaufen auf einem zugefrorenen Teich/See im Feld. Das Eis schmolz, er ertrank, der Schal blieb an der Oberfläche.",
    },
    {
        id: "initial_20",
        title: "Das Paket in der Wüste",
        difficulty: "Schwer",
        riddle: "Ein Mann liegt tot in der Wüste. Das Einzige in seiner Nähe ist eine kleine, geschlossene Kiste.",
        solution: "In der Kiste war eine Giftschlange, die er schmuggeln wollte. Sie ist ausgekommen und hat ihn gebissen.",
    },
    {
        id: "initial_21",
        title: "Die Hütte im Wald",
        difficulty: "Schwer",
        riddle: "Ein Mann wird tot in einer Hütte im Wald gefunden. Die einzige Tür war von innen verriegelt, ein kleines, hohes Fenster ebenfalls von innen. Der Mann starb an Unterkühlung.",
        solution: "Die 'Hütte' war der Rumpf eines abgestürzten Flugzeugs in einer verschneiten Gegend. Er überlebte den Absturz, erfror dann aber.",
    },
    {
        id: "initial_22",
        title: "Der kleinste Schwertschlucker",
        difficulty: "Mittel",
        riddle: "Der kleinste Mann der Welt wird tot gefunden.",
        solution: "Er war der Schwertschlucker im Zirkus. Jemand hat aus Spaß seine Stelzen versteckt, auf denen er immer stand, um die Schwerter sicher zu schlucken. Ohne sie schluckte er zu tief.",
    },
    {
        id: "initial_23",
        title: "Sägemehlhaufen",
        difficulty: "Mittel",
        riddle: "Ein Mann liegt tot in einem Haufen Sägemehl.",
        solution: "Er war ein kleinwüchsiger Mann, der in einem Sägewerk arbeitete und in den großen Sägemehltrichter gefallen und erstickt ist.",
    },
    {
        id: "initial_24",
        title: "Die zwei Pillen",
        difficulty: "Schwer",
        riddle: "Ein Entführer gibt einer Frau die Wahl zwischen zwei Pillen. Sie nimmt eine, der Entführer lässt sie gehen.",
        solution: "Eine Pille war harmlos, die andere tödlich. Die Frau nahm eine Pille, warf sie aber unbemerkt weg (oder versteckte sie). Der Entführer, der die andere Pille für sich behielt (oder dachte, die Frau hätte die tödliche gewählt, um einer schlimmeren Qual zu entgehen), war entweder beeindruckt oder verwirrt und ließ sie frei. Klassische Lösung: Sie nahm eine, der Entführer nahm die andere. Der Entführer starb. (Das Wasserglas neben ihr war vergiftet, nicht die Pillen, oder sie hatte das Gegengift). Beliebt: Sie teilte ihre Pille und bot dem Entführer die Hälfte an; er lehnte ab, da er nicht wusste, welche Pille es ist.",
    },
    {
        id: "initial_25",
        title: "Das Buch des Todes",
        difficulty: "Mittel",
        riddle: "Eine Frau kauft ein neues Buch und beginnt zu lesen. Sie beendet es nie, stirbt aber deswegen.",
        solution: "Sie las auf einem hohen Balkon, vertiefte sich so sehr in das Buch, dass sie sich zu weit hinauslehnte und hinunterfiel.",
    },
    {
        id: "initial_26",
        title: "Das offene Fenster",
        difficulty: "Leicht",
        riddle: "Ein Mann liegt tot in einem verschlossenen Raum mit einem offenen Fenster. Das Einzige im Raum sind eine Wasserpfütze und Glasscherben.",
        solution: "Der 'Mann' war ein Goldfisch. Eine Katze kam durch das offene Fenster, warf das Goldfischglas um und verschwand wieder.",
    },
    {
        id: "initial_27",
        title: "Der Chirurg",
        difficulty: "Leicht",
        riddle: "Ein Chirurg darf seinen eigenen Sohn nicht operieren.",
        solution: "Der Chirurg ist die Mutter des Jungen.",
    },
    {
        id: "initial_28",
        title: "Der Gehängte und die Pfütze",
        difficulty: "Mittel",
        riddle: "Ein Mann wird erhängt in einem leeren, verschlossenen Raum gefunden. Unter seinen Füßen befindet sich eine Wasserpfütze.",
        solution: "Er stand auf einem Eisblock, der inzwischen geschmolzen ist.",
    },
    {
        id: "initial_29",
        title: "Selbstmord im Radio",
        difficulty: "Schwer",
        riddle: "Ein Mann fährt Auto. Er schaltet das Radio ein, hört eine Minute zu, fährt dann rechts ran und erschießt sich.",
        solution: "Er war ein DJ, der gerade entlassen worden war. Im Radio lief ein voraufgezeichnetes Segment seiner Show, was ihn realisieren ließ, dass er alles verloren hatte.",
    },
    {
        id: "initial_30",
        title: "Das tödliche Geburtstagsgeschenk",
        difficulty: "Schwer",
        riddle: "Ein Mann erhält ein Geschenk zum Geburtstag. Er öffnet es, betrachtet es und wirft es sofort von einer Klippe.",
        solution: "Es war eine Voodoo-Puppe von ihm selbst, und er litt unter einer schrecklichen Krankheit. Er versuchte, sein Leiden zu beenden. (Viele Interpretationen möglich, z.B. ein defekter Fallschirm, den er als erfahrener Springer sicher entsorgt).",
    },
    {
        id: "initial_31",
        title: "Der einsame Fahrer",
        difficulty: "Leicht",
        riddle: "Ein Mann fährt allein in seinem Auto, als er unerklärlicherweise eine Vollbremsung macht.",
        solution: "Eine Spinne seilte sich von der Sonnenblende direkt vor sein Gesicht ab.",
    },
    {
        id: "initial_32",
        title: "Das letzte Mahl",
        difficulty: "Mittel",
        riddle: "Ein Mann isst in einem Restaurant. Er bezahlt, gibt ein gutes Trinkgeld, geht nach Hause und erschießt sich.",
        solution: "Er war ein berühmter Restaurantkritiker und es war das absolut beste Mahl seines Lebens. Er wusste, er würde nie wieder etwas Besseres erleben und beendete sein Leben auf diesem Höhepunkt.",
    },
    {
        id: "initial_33",
        title: "Zerrissene Zeitung",
        difficulty: "Mittel",
        riddle: "Ein Mann wird tot in seinem Arbeitszimmer gefunden, umgeben von zerrissenen Zeitungsstücken.",
        solution: "Er war ein spielsüchtiger Pferdewetter. Die zerrissenen Stücke waren Wettscheine und der Sportteil der Zeitung, der zeigte, dass sein Pferd verloren hatte und er ruiniert war.",
    },
    {
        id: "initial_34",
        title: "Der Arm im Paket",
        difficulty: "Mittel",
        riddle: "Ein Mann in einem Postamt hält ein Paket. Er schaut hinein, wird blass und fällt in Ohnmacht.",
        solution: "Er arbeitete in einer Firma für Prothesen und hatte versehentlich seine eigene Armprothese an einen Kunden geschickt. Das Paket, das er hielt, war die Rücksendung seiner eigenen Prothese.",
    },
    {
        id: "initial_35",
        title: "Die Frau in der Garage",
        difficulty: "Mittel",
        riddle: "Eine Frau wird tot in ihrem Auto in einer geschlossenen Garage gefunden. Der Motor des Autos ist aus, die Schlüssel stecken nicht.",
        solution: "Sie starb an einer Kohlenmonoxidvergiftung. Sie hatte den Wagen gestartet, um die Garage zu heizen oder um loszufahren, fiel dann aber in Schlaf oder wurde ohnmächtig, bevor sie den Motor wieder ausschalten oder das Tor öffnen konnte. Alternativ: Sie wollte nur kurz etwas aus dem Auto holen, ließ den Motor laufen, vergaß ihn und kam später wieder, als die Garage schon voller CO war.",
    },
    {
        id: "initial_36",
        title: "Die unterbrochene Vorstellung",
        difficulty: "Leicht",
        riddle: "Während einer Theatervorstellung fällt ein Schauspieler plötzlich tot auf der Bühne um. Das Publikum denkt, es sei Teil der Show, bis es zu spät ist.",
        solution: "Die Requisitenpistole war versehentlich mit einer echten Kugel statt einer Platzpatrone geladen.",
    },
    {
        id: "initial_37",
        title: "Der Schlaflose",
        difficulty: "Leicht",
        riddle: "Ein Mann konnte nicht schlafen. Er tätigte einen Anruf, sagte nichts und legte auf. Endlich konnte er schlafen.",
        solution: "Sein Nachbar schnarchte laut. Er rief den Nachbarn an, um ihn aufzuwecken und so das Schnarchen zu unterbrechen.",
    },
    {
        id: "initial_38",
        title: "Der Taucher im Wald",
        difficulty: "Schwer",
        riddle: "Ein Mann in vollem Taucheranzug wird tot in einem abgebrannten Waldstück gefunden.",
        solution: "Er tauchte in einem nahegelegenen See. Ein Löschflugzeug nahm ihn zusammen mit Wasser auf, um den Waldbrand zu bekämpfen, und warf ihn über dem Feuer ab.",
    },
    {
        id: "initial_39",
        title: "Der Mann auf dem Eis",
        difficulty: "Mittel",
        riddle: "Ein Mann wird tot auf einer Eisfläche gefunden. Nur eine einzige, gerade Linie führt zu ihm.",
        solution: "Er war ein Eiskunstläufer, der während einer Kür bei einer perfekt geraden Gleitfigur einen Herzinfarkt erlitt.",
    },
    {
        id: "initial_40",
        title: "Der unglückliche Spieler",
        difficulty: "Leicht",
        riddle: "Ein Mann verlässt ein Casino, steigt in ein Taxi und sagt zum Fahrer: 'Fahren Sie mich zur nächsten Brücke.'",
        solution: "Er hat sein ganzes Geld verspielt und beabsichtigte, von der Brücke zu springen.",
    },
    {
        id: "initial_41",
        title: "Das perfekte Verbrechen",
        difficulty: "Leicht",
        riddle: "Eine Frau tötet ihren Mann mit einem Eiszapfen. Der Eiszapfen schmilzt und hinterlässt keine Mordwaffe.",
        solution: "Die Lösung steht im Rätsel. Der Eiszapfen schmolz.",
    },
    {
        id: "initial_42",
        title: "Die Botschaft des Imkers",
        difficulty: "Schwer",
        riddle: "Ein Mann liegt tot in einem verschlossenen Raum. Der einzige Hinweis ist ein Zettel mit der Aufschrift '2B or not 2B'.",
        solution: "Er war Imker. Zwei seiner Bienen ('Two Bee') hatten ihn gestochen und er erlitt einen tödlichen allergischen Schock.",
    },
    {
        id: "initial_43",
        title: "Der blinde Passagier",
        difficulty: "Mittel",
        riddle: "Ein Mann springt von einem Schiff. Sekunden später bereut er es, doch es ist zu spät.",
        solution: "Er war ein blinder Passagier auf einem U-Boot. Das U-Boot war gerade beim Auftauchen, und er dachte, sie wären an Land.",
    },
    {
        id: "initial_44",
        title: "Der Mann in der Telefonzelle",
        difficulty: "Mittel",
        riddle: "Ein Mann liegt tot in einer Telefonzelle. Die Scheiben sind von innen zersprungen, aber nicht nach außen.",
        solution: "Er war ein Opernsänger, der eine extrem hohe Note übte. Durch die Akustik der Telefonzelle und die Resonanz zerbarsten die Scheiben nach innen und verletzten ihn tödlich.",
    },
    {
        id: "initial_45",
        title: "Die Frau und der Vogel",
        difficulty: "Schwer",
        riddle: "Eine Frau liegt tot in ihrem Haus. Neben ihr steht ein offener Vogelkäfig und ein toter Kanarienvogel.",
        solution: "Die Frau war blind. Der Kanarienvogel diente ihr als 'Warnsystem' für Gaslecks (wie früher im Bergbau). Das Gasleck tötete zuerst den Vogel, dann die Frau, bevor sie reagieren konnte.",
    },
    {
        id: "initial_46",
        title: "Der abgeschlagene Kopf",
        difficulty: "Mittel",
        riddle: "Ein Mann findet einen abgeschlagenen Kopf in seiner Frühstücksbox.",
        solution: "Der Mann ist Archäologe oder Paläontologe und hat eine sehr seltene und wertvolle Fossilie (einen versteinerten Kopf) gefunden und für den sicheren Transport in seiner Box aufbewahrt.",
    },
    {
        id: "initial_47",
        title: "Der Mann im Aufzugsschacht",
        difficulty: "Schwer",
        riddle: "Ein Mann liegt tot am Boden eines Aufzugschachts. Der Aufzug ist intakt und befindet sich im obersten Stockwerk.",
        solution: "Der Mann war ein Fensterputzer, der sich vom Dach abseilte. Er dachte, der Aufzug sei auf seiner Etage, trat auf dessen Dach, aber der Aufzug fuhr plötzlich los, und er stürzte in den Schacht.",
    },
    {
        id: "initial_48",
        title: "Der verschwundene Zug",
        difficulty: "Mittel",
        riddle: "Ein Zug fährt in einen Tunnel und kommt nie wieder heraus. Es gibt keine Anzeichen eines Unfalls im Tunnel.",
        solution: "Der Tunnel war sehr kurz und der Zug fuhr einfach durch, ohne dass die Beobachter am Tunneleingang das andere Ende sehen konnten. Oder: Der 'Zug' war eine Modell-Eisenbahn und wurde einfach vom Tisch genommen.",
    },
    {
        id: "initial_49",
        title: "Der Schuss im Dunkeln",
        difficulty: "Leicht",
        riddle: "Ein Mann hört einen Schuss, macht das Licht an und sieht eine Leiche. Er macht das Licht wieder aus.",
        solution: "Er hat gerade eine Motte oder ein anderes Insekt mit einer zusammengerollten Zeitung (dem 'Schuss') erschlagen. Die 'Leiche' ist das Insekt.",
    },
    {
        id: "initial_50",
        title: "Der Mann ohne Arme und Beine",
        difficulty: "Mittel",
        riddle: "Ein Mann ohne Arme und Beine liegt tot vor einer Haustür.",
        solution: "Er hieß 'Matt'. (Auf Englisch: 'mat' = Fußmatte).",
    },
	{
		id: "initial_51",
		title: "Der Felsen am Berg",
		difficulty: "Schwer",
		riddle: "Ein Mann schiebt jeden Tag einen Felsen einen Berg hinauf. Am nächsten Morgen liegt der Felsen wieder unten. Warum?",
		solution: "Der Mann ist Wärter in einem Steinbruch. Der Felsen dient als Warnsignal. Wenn er nachts herunterrollt, alarmiert er die Arbeiter vor Gefahren.",
	},
	{
		id: "initial_52",
		title: "Die stille Flasche",
		difficulty: "Mittel",
		riddle: "Eine Flasche wird auf den Tisch gestellt. Jeder, der sie sieht, beginnt zu weinen.",
		solution: "Die Flasche enthält die Asche eines verstorbenen Kindes.",
	},
	{
		id: "initial_53",
		title: "Das leere Telefonat",
		difficulty: "Leicht",
		riddle: "Ein Mann ruft eine Nummer an, sagt kein Wort, und die Person am anderen Ende weiß sofort, was passiert ist.",
		solution: "Der Anrufer ist stumm und nutzt einen Notfalldienst, bei dem Schweigen ein Codewort für einen Überfall ist.",
	},
	{
		id: "initial_54",
		title: "Der einsame Wächter",
		difficulty: "Schwer",
		riddle: "Ein Mann bewacht seit 20 Jahren ein leeres Gebäude. Warum?",
		solution: "Er ist der Nachtwächter eines Museums. Das Gebäude wurde abgerissen, aber sein Vertrag läuft noch – niemand hat ihn informiert.",
	},
	{
		id: "initial_55",
		title: "Das Buch ohne Worte",
		difficulty: "Mittel",
		riddle: "Eine Frau liest ein Buch, das keine einzige geschriebene Seite enthält. Trotzdem weint sie.",
		solution: "Es ist ein Fotoalbum mit Bildern ihres verstorbenen Partners.",
	}
];